import Head from 'next/head';

import { userFromCookie } from '../utils';

const Home = ({}) => {
  return (
    <div>
      <Head>
        <title>Demo: Next.js on Rails</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex flex-col'>
        <header className='flex flex-col items-center justify-center mt-10'>
          <h1 className='text-5xl font-extrabold'>
            Welcome to <span className='text-blue-500'>Next.js</span> on{' '}
            <span className='text-blue-500'>Rails</span>
          </h1>
          <p className='text-xl font-bold mt-10'>UI components available for use:</p>
        </header>
        
      </div>
    </div>
  );
};

export async function getServerSideProps({ req }) {
  const user = userFromCookie(req);

  return {
    props: {
      loggedIn: user ? user.token.length > 0 : false,
    },
  };
}

export default Home;
